language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
services: postgresql
before_script:
  - psql -c 'create database microblog;' -U postgres
# command to run tests
script: python tests.py