"""empty message

Revision ID: 13d55b9cbd58
Revises: 495082ab7842
Create Date: 2014-03-14 12:34:24.262588

"""

# revision identifiers, used by Alembic.
revision = '13d55b9cbd58'
down_revision = '495082ab7842'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('reg_key', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'users', ['reg_key'])
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    op.drop_constraint(None, 'users')
    op.drop_column('users', 'reg_key')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
