"""empty message

Revision ID: 1bdf2736c9f8
Revises: None
Create Date: 2014-03-11 13:34:46.816482

"""

# revision identifiers, used by Alembic.
revision = '1bdf2736c9f8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
