"""empty message

Revision ID: 1dd20e64ed7d
Revises: None
Create Date: 2014-03-14 15:38:43.223598

"""

# revision identifiers, used by Alembic.
revision = '1dd20e64ed7d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
