"""empty message

Revision ID: 2cd044c3654d
Revises: 1dd20e64ed7d
Create Date: 2014-03-14 15:55:24.345490

"""

# revision identifiers, used by Alembic.
revision = '2cd044c3654d'
down_revision = '1dd20e64ed7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temp_users', 'regkey',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temp_users', 'regkey',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    ### end Alembic commands ###
