"""empty message

Revision ID: 495082ab7842
Revises: 2ced315ca2d2
Create Date: 2014-03-13 13:42:30.510765

"""

# revision identifiers, used by Alembic.
revision = '495082ab7842'
down_revision = '2ced315ca2d2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'auth_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'auth_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
